### ISSUE TITLE
Follow

### ISSUE THREAD

**Issue by Details0824** [ain-soph/trojanzoo_sphinx_theme#13]
Hello, I'd like to try to do the work that you have done.I just want to  removed all Pytorch related stuff of the pytorch_sphinx_theme. I also want to removes all other unnecessary items, making it a pure Doc template to edit my own docs. Do you have instructions for the relevant change process? Or how can I follow your project to build my own documentation, what changes do I need to make?

**Comment by ain-soph** [comment]
Yeah, I think this work has already done that. Do you have any other demand?

You can check the example usage from those demos

https://ain-soph.github.io/trojanzoo_sphinx_theme/  
https://ain-soph.github.io/alpsplot/  
https://ain-soph.github.io/trojanzoo/

**Comment by ain-soph** [comment]
I recommend you to check alpsplot and trojanzoo docs if you want to make python docs

**Comment by Details0824** [comment]
THANKS for replying. Your work is useful for me. I had tried to build your work, then i use `html_theme = 'trojanzoo_sphinx_theme'` to rebuild a new html. And i build it successfully. However,there was a exception (exception: 'logo'). And don't have the logo in top left of the new html. 

If i don't revise the code, there should have a logo of your's(TrojanZoo).Right?But there is nothing.
how can i to revise it to my own logo?

**Comment by ain-soph** [comment]
Logo images are put here: https://github.com/ain-soph/trojanzoo_sphinx_theme/tree/main/docs/source/images/logo  

While the logo config is here: https://github.com/ain-soph/trojanzoo_sphinx_theme/blob/1a5f947fdef16906e8c06465c8ebbbeb584dfabf/docs/source/conf.py#L40-L54

**Comment by Details0824** [comment]
Thanks. I implemented the replacement of the logo. But the logo display on the website is too small, is there any way to change the size?

**Comment by ain-soph** [comment]
The logo images are set here in the js. You may find a way to resize that.

https://github.com/ain-soph/trojanzoo_sphinx_theme/blob/d3a36675c42dc2563f452e8b3d29a04691203a83/trojanzoo_sphinx_theme/layout.html#L272-L278

**Comment by Details0824** [comment]
First of all, thank you very much for your careful explanation.
When i use the `.. autosummary::` to build a table, the first column is the function list and the second column is short summary.
The problem is the first column is too narrow, the function's name will be split to lines. But i see the autosummary of the Pytorch theme uesd don't have the problem. 

1. Do you know if the Pytorch theme use any customizing templates of autosummary? 
2. Or could you teach me how to adjust column width of autosummary table？

Thank you again from the bottom of my heart！

**Comment by Details0824** [comment]
> First of all, thank you very much for your careful explanation. When i use the `.. autosummary::` to build a table, the first column is the function list and the second column is short summary. The problem is the first column is too narrow, the function's name will be split to lines. But i see the autosummary of the Pytorch theme uesd don't have the problem.
> 
> 1. Do you know if the Pytorch theme use any customizing templates of autosummary?
> 2. Or could you teach me how to adjust column width of autosummary table？
> 
> Thank you again from the bottom of my heart！

I find the customizing templates of the autosummary  in the ''source/_templates"  folder. Is the way to use this file is to put this autosummary directly under my folder ''source/_templates" ?But it seems have no change.

**Comment by ain-soph** [comment]
Good question. I actually never use autosummary before. Let me test that in the weekends.

And it’ll be better if you can attach a snapshot.

**Comment by ain-soph** [comment]
> > First of all, thank you very much for your careful explanation. When i use the `.. autosummary::` to build a table, the first column is the function list and the second column is short summary. The problem is the first column is too narrow, the function's name will be split to lines. But i see the autosummary of the Pytorch theme uesd don't have the problem.
> > 
> > 1. Do you know if the Pytorch theme use any customizing templates of autosummary?
> > 2. Or could you teach me how to adjust column width of autosummary table？
> > 
> > Thank you again from the bottom of my heart！
> 
> I find the customizing templates of the autosummary in the ''source/_templates" folder. Is the way to use this file is to put this autosummary directly under my folder ''source/_templates" ?But it seems have no change.


You need to add template folder in your conf like this. Have you done that?

https://github.com/pytorch/pytorch/blob/645a9235f0b896b440dc52972df87fc6359a5980/docs/source/conf.py#L85

**Comment by ain-soph** [comment]
Btw, may I ask what’s the scenario of using autosummary? Is it because you prefer one method/class per page?

From your description, I guess it’s something like this: 
https://pytorch.org/docs/stable/nn.functional.html

**Comment by Details0824** [comment]
> add template folder in your conf like this. Ha

Yes, I had add template folder in my conf.py like this.

**Comment by Details0824** [comment]
> Btw, may I ask what’s the scenario of using autosummary? Is it because you prefer one method/class per page?
> 
> From your description, I guess it’s something like this: https://pytorch.org/docs/stable/nn.functional.html

Yes, This is what I want to achieve, the first and second columns have similar column widths. But the problem is as I described, when I use autosummary, the width of the first column is too narrow to accommodate only one word.

**Comment by Details0824** [comment]
> Good question. I actually never use autosummary before. Let me test that in the weekends.
> 
> And it’ll be better if you can attach a snapshot.



I haven't uploaded the documentation to GitHub or gitlab, here's a screenshot from my computer.

**Comment by ain-soph** [comment]
Sorry for the latency. Will deal with it in this week.

**Comment by Details0824** [comment]
> 
Nevermind, I tried `.. autosummary::` again this morning with no changes, and the magic happened, it returned to normal style of Pytorch.So i don't think you need to deal with it anymore.But you can check out pytorch's autosummary templates and design and implement related templates.

I am trying to understand and modify the interface and links of the web page now. If I have any questions, I will continue to consult you. Hope you can answer them.Thanks very much.Have a nice week.
